### ISSUE TITLE
Solar Potential Calculation on HQ

### ISSUE THREAD

**Issue by matthiassulzer** [architecture-building-systems/CityEnergyAnalyst#2645]
**Describe the bug**
Rey, everything works fine…. Exept the calculation of the solar potential:
City Energy Analyst version 2.32.0
Running `cea photovoltaic` with the following parameters:
- general:scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- solar:type-pvpanel = PV1
  (default: PV1)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- solar:panel-on-roof = True
  (default: True)
- solar:panel-on-wall = True
  (default: True)
- solar:annual-radiation-threshold = 800.0
  (default: 800.0)
- solar:solar-window-solstice = 4
  (default: 4)
Running photovoltaic with scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
Running photovoltaic with annual-radiation-threshold-kWh/m2 = 800.0
Running photovoltaic with panel-on-roof = True
Running photovoltaic with panel-on-wall = True
Running photovoltaic with solar-window-solstice = 4
Running photovoltaic with type-pvpanel = PV1
Using 3 CPU's
calculating solar properties doneTraceback (most recent call last):
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\technologies\solar\photovoltaic.py", line 782, in main
    buildings_names)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 97, in wrapper
    result = map_result.get()
  File "C:\Users\sum\Documents\CEA\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
ValueError: operands could not be broadcast together with shapes (8784,) (8784,) (8784,) () (8760,) (8760,) () () () 

gathering properties of PV panel
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
Could you give me a hint, what is wrong?

Best,

Matthias

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by daren-thomas** [comment]
Maybe due to `solar:annual-radiation-threshold = 800.0` some of the buildings are being filtered out. @matthiassulzer  would you mind trying to re-run this with `annual-radiation-threshold = 400.0`? Does that work?

**Comment by matthiassulzer** [comment]
Hi Daren

Thanks for the hint… unfortunately the error still occurs:
Job Output for 1 - photovoltaic
City Energy Analyst version 2.32.0
Running `cea photovoltaic` with the following parameters:
- general:scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- solar:type-pvpanel = PV1
  (default: PV1)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- solar:panel-on-roof = True
  (default: True)
- solar:panel-on-wall = True
  (default: True)
- solar:annual-radiation-threshold = 400.0
  (default: 800.0)
- solar:solar-window-solstice = 4
  (default: 4)
Running photovoltaic with scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
Running photovoltaic with annual-radiation-threshold-kWh/m2 = 400.0
Running photovoltaic with panel-on-roof = True
Running photovoltaic with panel-on-wall = True
Running photovoltaic with solar-window-solstice = 4
Running photovoltaic with type-pvpanel = PV1
Using 3 CPU's
calculating solar properties done
gathering properties of PV panel
Traceback (most recent call last):
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\technologies\solar\photovoltaic.py", line 782, in main
    buildings_names)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 97, in wrapper
    result = map_result.get()
  File "C:\Users\sum\Documents\CEA\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
ValueError: operands could not be broadcast together with shapes (8784,) (8784,) (8784,) () (8760,) (8760,) () () ()

filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
calculating solar properties done
Best,

Matthias

Von: Daren Thomas <notifications@github.com>
Gesendet: Donnerstag, 19. März 2020 12:01
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


Maybe due to solar:annual-radiation-threshold = 800.0 some of the buildings are being filtered out. @matthiassulzer<https://github.com/matthiassulzer> would you mind trying to re-run this with annual-radiation-threshold = 400.0? Does that work?

**Comment by reyery** [comment]
Hmm. I think there is something different with the radiation output files. 
```
ValueError: operands could not be broadcast together with shapes (8784,) (8784,) (8784,) () (8760,) (8760,) () () ()
```

The magical number **8760** is actually the number of hours in a year. 

So the radiation file for a building is supposed to have **8760** rows of radiation data.

<img width="100%" alt="rqad" src="https://user-images.githubusercontent.com/34395415/77156064-8f216780-6ad9-11ea-8e31-29b578f3482f.PNG">

But the radiation files that were created have **8784** rows = **24** hours difference = **1** day. And since the weather file is based on **2016** (leap year),  a leap year day was probably included when calculating radiation. 

<img width="100%" alt="ras" src="https://user-images.githubusercontent.com/34395415/77156006-7022d580-6ad9-11ea-8ae0-811282f6a069.PNG">

I'm still investigating why the radiation script is doing this. Because the weather file provided has exactly **8760** records even though from 2016, so radiation could be adding that extra row somewhere.

**Comment by matthiassulzer** [comment]
Many thanks for your help. Hopefully you find the mistake...

Freundliche Grüsse

Matthias Sulzer

Am 20.03.2020 um 12:27 schrieb Reynold Mok <notifications@github.com>:

﻿

Hmm. I think there is something different with the radiation output files.

ValueError: operands could not be broadcast together with shapes (8784,) (8784,) (8784,) () (8760,) (8760,) () () ()


The magical number 8760 is actually the number of hours in a year.

So the radiation file for a building is supposed to have 8760 rows of radiation data.

[rqad]<https://user-images.githubusercontent.com/34395415/77156064-8f216780-6ad9-11ea-8e31-29b578f3482f.PNG>

But the radiation files that were created have 8784 rows = 24 hours difference = 1 day. And since the weather file is based on 2016 (leap year), a leap year day was probably included when calculating radiation.

[ras]<https://user-images.githubusercontent.com/34395415/77156006-7022d580-6ad9-11ea-8ae0-811282f6a069.PNG>

I'm still investigating why the radiation script is doing this. Because the weather file provided has exactly 8760 records even though from 2016, so radiation could be adding that extra row somewhere.

**Comment by reyery** [comment]
I think what is happening here is that DAYSIM (`epw2wea`) is including the leap year day when converting the .epw file that we provide to the .wea file that it uses for calculation. 

So I think we might have to handle this (leap year) on our end _(unless there is a parameter/property that we can include in the header file or command to do this, but the DAYSIM website is down now so I'm not sure_), by removing extra rows if needed by making sure it has the same number of rows as the provided weather file since we are calculating solar potentials against that.

**Comment by matthiassulzer** [comment]
Perfect. I am waiting for an update on github. Please advise me, when I can request a pull….

Von: Reynold Mok <notifications@github.com>
Gesendet: Freitag, 20. März 2020 13:03
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


I think what is happening here is that DAYSIM (epw2wea) is including the leap year day when converting the .epw file that we provide to the .wea file that it uses for calculation.

So I think we might have to handle this (leap year) on our end (unless there is a parameter/property that we can include in the header file or command to do this, but the DAYSIM website is down now so I'm not sure), by removing extra rows if needed by making sure it has the same number of rows as the provided weather file since we are calculating solar potentials against that.

**Comment by reyery** [comment]
Ah of course! The data for the leap day is actually in the weather file! That is why DAYSIM has the information for the extra rows, since it is reading straight from the file, albeit the converted one. There is nothing wrong with what DAYSIM was doing but how we are reading the weather file on our end.

![image](https://user-images.githubusercontent.com/34395415/77226931-feb95480-6bb6-11ea-9a7d-aaa93d98a7cd.png)

For some reason our `epwreader` is only including the `HOURS_IN_YEAR` number of rows in L30. Any ideas why it was done like this? @JIMENOFONSECA. Maybe to keep the number of rows the same? But would that affect any other calculation if it were different? 

In the case of a leap year data, for 31 December is left out.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/a7816e60c10558ecd59208bbe0efb095c945bc1f/cea/utilities/epwreader.py#L21-L38

**Comment by JIMENOFONSECA** [comment]
I think we need to leave out the 29th of February (which is the difference with the leap year). The best is that the epw reader do this check, if 29th of february exist, then erase the day. Confirm that the file has 8760 entries.


On 21 Mar 2020, 21:12 +0800, Reynold Mok <notifications@github.com>, wrote:

Ah of course! The data for the leap day is actually in the weather file! That is why DAYSIM has the information for the extra rows, since it is reading straight from the file, albeit the converted one. There is nothing wrong with what DAYSIM was doing but how we are reading the weather file on our end.

[image]<https://user-images.githubusercontent.com/34395415/77226931-feb95480-6bb6-11ea-9a7d-aaa93d98a7cd.png>

For some reason our epwreader is only including the HOURS_IN_YEAR number of rows in L30. Any ideas why it was done like this? @JIMENOFONSECA<https://github.com/JIMENOFONSECA>. Maybe to keep the number of rows the same? But would that affect any other calculation if it were different?

In the case of a leap year data, for 31 December is left out.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/a7816e60c10558ecd59208bbe0efb095c945bc1f/cea/utilities/epwreader.py#L21-L38

**Comment by reyery** [comment]
@JIMENOFONSECA I have removed the leap day in `epwreader` but it still gives the same error since DAYSIM would still include the leap day. I think we would still have to edit the radiation output results if you really want to maintain the 8760 rows everywhere.

**Comment by JIMENOFONSECA** [comment]
Yes, let’s do that.

Jimeno

________________________

Jimeno A. Fonseca
Dr. Sc. ETH Zurich

Senior Researcher
Singapore ETH-Centre (SEC)<https://sec.ethz.ch/>

Project Coordinator
Multi-Scale Energy Systems (MuSES)<https://fcl.ethz.ch/research/high-density-cities/multi-scale-energy-systems.html>

Product Owner & Developer
City Energy Analyst (CEA)<https://cityenergyanalyst.com/>

Principal Investigator
Cooling Singapore (CS1.5)<https://www.coolingsingapore.sg/>
Future Resilience Systems (FRS)<https://frs.ethz.ch/research/cyber-physical-systems/digital-twin-enabled-system-resilience.html>

On 24 Mar 2020, 16:26 +0800, Reynold Mok <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I have removed the leap day in epwreader but it still gives the same error since DAYSIM would still include the leap day. I think we would still have to edit the radiation output results if you really want to maintain the 8760 rows everywhere.

**Comment by matthiassulzer** [comment]
Hi Rey

Please let me know, if you fixed the solar problem. Thanks.

And could you advise me, why no jobs are getting executed, after I pulled all new changes from GitHub?
[cid:image001.png@01D602AC.5830EC40]

Best,

Matthias

Von: Reynold Mok <notifications@github.com>
Gesendet: Freitag, 20. März 2020 13:03
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


I think what is happening here is that DAYSIM (epw2wea) is including the leap year day when converting the .epw file that we provide to the .wea file that it uses for calculation.

So I think we might have to handle this (leap year) on our end (unless there is a parameter/property that we can include in the header file or command to do this, but the DAYSIM website is down now so I'm not sure), by removing extra rows if needed by making sure it has the same number of rows as the provided weather file since we are calculating solar potentials against that.

**Comment by reyery** [comment]
@matthiassulzer you would need to overwrite the interface with the latest one which was not included in the current release. There was a change in master that has made the one that you have installed not able to send jobs to CEA. 

You could download the pre-release version [here](https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/releases/download/v3.0.2/win-unpacked.7z) and extract to overwrite the one that you have.

![image](https://user-images.githubusercontent.com/34395415/77538743-31c35700-6edb-11ea-948c-71337d5d0a0a.png)

**Comment by matthiassulzer** [comment]
Perfect! It works agin. Many thanks ☺

Von: Reynold Mok <notifications@github.com>
Gesendet: Mittwoch, 25. März 2020 13:58
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> you would need to overwrite the interface with the latest one which was not included in the current release. There was a change in master that has made the one that you have installed not able to send jobs to CEA.

You could download the pre-release version here<https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/releases/download/v3.0.2/win-unpacked.7z> and extract to overwrite the one that you have.

[image]<https://user-images.githubusercontent.com/34395415/77538743-31c35700-6edb-11ea-948c-71337d5d0a0a.png>

**Comment by matthiassulzer** [comment]
Hi Rey

I hope you progress with Daysim. I just recognized a minor tipper: relative Demand and Supply should be W/m2 instead of kW/m2.

Best,

M
[cid:image002.jpg@01D6050B.E5908080]

Von: Reynold Mok <notifications@github.com>
Gesendet: Freitag, 20. März 2020 13:03
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


I think what is happening here is that DAYSIM (epw2wea) is including the leap year day when converting the .epw file that we provide to the .wea file that it uses for calculation.

So I think we might have to handle this (leap year) on our end (unless there is a parameter/property that we can include in the header file or command to do this, but the DAYSIM website is down now so I'm not sure), by removing extra rows if needed by making sure it has the same number of rows as the provided weather file since we are calculating solar potentials against that.

**Comment by reyery** [comment]
@matthiassulzer I have already come up with a fix and an waiting for testing to pass before merging it to master.

**Comment by matthiassulzer** [comment]
Ufff. Many thanks. I am looking forward to it.

Von: Reynold Mok <notifications@github.com>
Gesendet: Mittwoch, 1. April 2020 11:39
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> I have already come up with a fix and an waiting for testing to pass before merging it to master.

**Comment by reyery** [comment]
>  I just recognized a minor tipper: relative Demand and Supply should be W/m2 instead of kW/m2.

@matthiassulzer, I am trying to find this variable but I am not too sure where it is from. May I know which one you are referring to?

**Comment by matthiassulzer** [comment]
Hi Rey

In the dash board: if I am choosing add plot, energy demand, peak demand, the graph shows in the section Relative (kW/m2). In my mind it should be W/m2. Clear?

[cid:image001.jpg@01D608DE.8C504100]

Von: Reynold Mok <notifications@github.com>
Gesendet: Donnerstag, 2. April 2020 09:16
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


I just recognized a minor tipper: relative Demand and Supply should be W/m2 instead of kW/m2.

@matthiassulzer<https://github.com/matthiassulzer>, I am trying to find this variable but I am not too sure where it is from. May I know which one you are referring to?

**Comment by matthiassulzer** [comment]
Hi Rey

How does it look like? Is the bug of the daysim solved? Thanks for a quick update.

Best,

Matthias

Von: Reynold Mok <notifications@github.com>
Gesendet: Mittwoch, 1. April 2020 11:39
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> I have already come up with a fix and an waiting for testing to pass before merging it to master.

**Comment by matthiassulzer** [comment]
Hi Shanshan

How are you? I hope you are well in Singapore. I am just wondering, why this issue is closed. There is still an error by calculating the solar potential. Many thanks for a short feedback.

Best,

Matthias

PS. We would like to use CEA for the MBS, hence we are looking for a quick solve of the error.


Von: Shanshan Hsieh <notifications@github.com>
Gesendet: Donnerstag, 9. April 2020 05:30
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


Closed #2645<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2645> via #2666<https://github.com/architecture-building-systems/CityEnergyAnalyst/pull/2666>.

**Comment by reyery** [comment]
@matthiassulzer I think this issue was closed automatically after we have merged the fix to master. You could try pulling this update using the Github application and try the calculations again.

**Comment by matthiassulzer** [comment]
Hi Rey

Thanks for the information. I pulled on github, run the weather helper on CEA, but still get the same error, when I am running PV/solar potential:

City Energy Analyst version 3.0.2
Running `cea photovoltaic-thermal` with the following parameters:
- general:scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\Plattenstrasse
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- solar:buildings = []
  (default: [])
- solar:type-pvpanel = PV1
  (default: PV1)
- solar:type-scpanel = FP
  (default: FP)
- solar:panel-on-roof = True
  (default: True)
- solar:panel-on-wall = True
  (default: True)
- solar:annual-radiation-threshold = 400.0
  (default: 800.0)
- solar:solar-window-solstice = 4
  (default: 4)
- solar:t-in-pvt = None
  (default: None)
Running photovoltaic-thermal with scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\Plattenstrasse
Running photovoltaic-thermal with annual-radiation-threshold-kWh/m2 = 400.0
Running photovoltaic-thermal with panel-on-roof = True
Running photovoltaic-thermal with panel-on-wall = True
Running photovoltaic-thermal with solar-window-solstice = 4
Running photovoltaic-thermal with t-in-pvt = None
Running photovoltaic-thermal with type-pvpanel = PV1
reading weather hourly_results_per_building done.
Using 3 CPU's
calculating solar properties done for building B1000
gathering properties of PVT collector panel for building B1000
filtering low potential sensor points done for building B1000
calculating optimal tile angle and separation done for building B1000
generating groups of sensor points done for building B1000Traceback (most recent call last):
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\technologies\solar\photovoltaic_thermal.py", line 695, in main
    building_names)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 97, in wrapper
    result = map_result.get()
  File "C:\Users\sum\Documents\CEA\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
ValueError: operands could not be broadcast together with shapes (8784,) (8784,) (8784,) () (8760,) (8760,) () () ()
Could you give me an advice?

Thanks,

Matthias

Von: Reynold Mok <notifications@github.com>
Gesendet: Donnerstag, 9. April 2020 11:08
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> I think this issue was closed automatically after we have merged the fix to master. You could try pulling this update using the Github application and try the calculations again.

**Comment by reyery** [comment]
@matthiassulzer you would have to rerun the `radiation` script also since the previous radiation results would still have the leap day.

**Comment by matthiassulzer** [comment]
Rey, you are the best! Many thanks.

Von: Reynold Mok <notifications@github.com>
Gesendet: Donnerstag, 9. April 2020 11:20
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> you would have to rerun the radiation script also since the previous radiation results would still have the leap day.

**Comment by matthiassulzer** [comment]
Hi Rey
I have application question: Can I only simulate one building? And how can I run the optimization for central? Do you have an idea? Thanks.

Best,

Matthias

Von: Reynold Mok <notifications@github.com>
Gesendet: Donnerstag, 9. April 2020 11:20
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> you would have to rerun the radiation script also since the previous radiation results would still have the leap day.

**Comment by reyery** [comment]
I'm not too sure it is possible to do optimization for one building right now. You could submit a request for this feature on GitHub if you want to do that.

**Comment by matthiassulzer** [comment]
Cool. Thx. I will do so.

Gruss

Matthias


Am 13.04.2020 um 10:16 schrieb Reynold Mok <notifications@github.com>:

﻿

I'm not too sure it is possible to do optimization for one building right now. You could submit a request for this feature on GitHub if you want to do that.

**Comment by matthiassulzer** [comment]
Hi Rey

Everything worked out well with the HQ case…. up to now. I got the following error:
City Energy Analyst version 3.1.0
Running `cea radiation` with the following parameters:
- general:scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- radiation:buildings = []
  (default: [])
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:consider-intersections = False
  (default: False)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = C:\Users\sum\Documents\CEA\CityEnergyAnalyst\Dependencies\Daysim
  (default: C:\Daysim\bin)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
- radiation:write-sensor-data = True
  (default: True)
verifying geometry files
C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ\inputs\building-geometry\zone.shp
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
getting geometry materials
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using 3 CPU's
Building B155084 done
Generating geometry for building 1 completed out of 14: B155084
Building B9083954 done
Generating geometry for building 2 completed out of 14: B9083954
Building B2367087 done
Generating geometry for building 3 completed out of 14: B2367087
Building B155082 done
Generating geometry for building 4 completed out of 14: B155082
Building B155068 done
Generating geometry for building 5 completed out of 14: B155068
Building B2367183a done
Generating geometry for building 6 completed out of 14: B2367183a
Building B155128b done
Generating geometry for building 7 completed out of 14: B155128b
Building B155069 done
Generating geometry for building 8 completed out of 14: B155069
Building B2367183 done
Generating geometry for building 9 completed out of 14: B2367183
Building B155083 done
Generating geometry for building 10 completed out of 14: B155083
Building B155080 done
Generating geometry for building 11 completed out of 14: B155080
Building B2367183b done
Generating geometry for building 12 completed out of 14: B2367183b
Building B155128 done
Generating geometry for building 13 completed out of 14: B155128
Building B155128a done
Generating geometry for building 14 completed out of 14: B155128a
Sending the scene: geometry and materials to daysim
         radiation_main: rad.base_file_path: c:\users\sum\appdata\local\temp\default_materials.rad
         radiation_main: rad.data_folder_path: c:\users\sum\appdata\local\temp
         radiation_main: rad.command_file: c:\users\sum\appdata\local\temp\command.txt
Traceback (most recent call last):
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 502, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.radiation)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 170, in radiation_singleprocessing
    weatherfile = epwreader.epw_reader(weather_path)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\epwreader.py", line 46, in epw_reader
    epw_data = result[~((date_range.month == 2) & (date_range.day == 29))].reset_index()
NameError: global name 'result' is not defined

         radiation_main: rad.rad_file_path: c:\users\sum\appdata\local\temp\geometry.rad
Could you please give me hint, what I should do?

Best,

Matthias

Von: Sulzer, Matthias
Gesendet: Donnerstag, 9. April 2020 11:30
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com>; architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

Rey, you are the best! Many thanks.

Von: Reynold Mok <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Donnerstag, 9. April 2020 11:20
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch<mailto:Matthias.Sulzer@empa.ch>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> you would have to rerun the radiation script also since the previous radiation results would still have the leap day.

**Comment by matthiassulzer** [comment]
… interesting: using Zürich SMA 2016 weather data, the error occurs. But using Zürich TMY 1990-2010 weather data, on error occurs.

Von: Sulzer, Matthias
Gesendet: Montag, 20. April 2020 19:40
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com>; 'architecture-building-systems/CityEnergyAnalyst' <CityEnergyAnalyst@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

Hi Rey

Everything worked out well with the HQ case…. up to now. I got the following error:
City Energy Analyst version 3.1.0
Running `cea radiation` with the following parameters:
- general:scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- radiation:buildings = []
  (default: [])
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:consider-intersections = False
  (default: False)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = C:\Users\sum\Documents\CEA\CityEnergyAnalyst\Dependencies\Daysim
  (default: C:\Daysim\bin)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
- radiation:write-sensor-data = True
  (default: True)
verifying geometry files
C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ\inputs\building-geometry\zone.shp
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
getting geometry materials
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using 3 CPU's
Building B155084 done
Generating geometry for building 1 completed out of 14: B155084
Building B9083954 done
Generating geometry for building 2 completed out of 14: B9083954
Building B2367087 done
Generating geometry for building 3 completed out of 14: B2367087
Building B155082 done
Generating geometry for building 4 completed out of 14: B155082
Building B155068 done
Generating geometry for building 5 completed out of 14: B155068
Building B2367183a done
Generating geometry for building 6 completed out of 14: B2367183a
Building B155128b done
Generating geometry for building 7 completed out of 14: B155128b
Building B155069 done
Generating geometry for building 8 completed out of 14: B155069
Building B2367183 done
Generating geometry for building 9 completed out of 14: B2367183
Building B155083 done
Generating geometry for building 10 completed out of 14: B155083
Building B155080 done
Generating geometry for building 11 completed out of 14: B155080
Building B2367183b done
Generating geometry for building 12 completed out of 14: B2367183b
Building B155128 done
Generating geometry for building 13 completed out of 14: B155128
Building B155128a done
Generating geometry for building 14 completed out of 14: B155128a
Sending the scene: geometry and materials to daysim
         radiation_main: rad.base_file_path: c:\users\sum\appdata\local\temp\default_materials.rad
         radiation_main: rad.data_folder_path: c:\users\sum\appdata\local\temp
         radiation_main: rad.command_file: c:\users\sum\appdata\local\temp\command.txt
Traceback (most recent call last):
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 502, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.radiation)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 170, in radiation_singleprocessing
    weatherfile = epwreader.epw_reader(weather_path)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\epwreader.py", line 46, in epw_reader
    epw_data = result[~((date_range.month == 2) & (date_range.day == 29))].reset_index()
NameError: global name 'result' is not defined

         radiation_main: rad.rad_file_path: c:\users\sum\appdata\local\temp\geometry.rad
Could you please give me hint, what I should do?

Best,

Matthias

Von: Sulzer, Matthias
Gesendet: Donnerstag, 9. April 2020 11:30
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com<mailto:reply@reply.github.com>>; architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

Rey, you are the best! Many thanks.

Von: Reynold Mok <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Donnerstag, 9. April 2020 11:20
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch<mailto:Matthias.Sulzer@empa.ch>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> you would have to rerun the radiation script also since the previous radiation results would still have the leap day.

**Comment by matthiassulzer** [comment]
Hi Rey

I just identified another bug in the graph:
Annual Costs for best individuals after 100 generations normalized to gross floor area
--> the cost are showed in absolute numbers instead of US$ per m2 GFA

Best,

Matthias

Von: Sulzer, Matthias
Gesendet: Montag, 20. April 2020 19:53
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com>; 'architecture-building-systems/CityEnergyAnalyst' <CityEnergyAnalyst@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

… interesting: using Zürich SMA 2016 weather data, the error occurs. But using Zürich TMY 1990-2010 weather data, on error occurs.

Von: Sulzer, Matthias
Gesendet: Montag, 20. April 2020 19:40
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com<mailto:reply@reply.github.com>>; 'architecture-building-systems/CityEnergyAnalyst' <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: 'Mention' <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

Hi Rey

Everything worked out well with the HQ case…. up to now. I got the following error:
City Energy Analyst version 3.1.0
Running `cea radiation` with the following parameters:
- general:scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- radiation:buildings = []
  (default: [])
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:consider-intersections = False
  (default: False)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = C:\Users\sum\Documents\CEA\CityEnergyAnalyst\Dependencies\Daysim
  (default: C:\Daysim\bin)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
- radiation:write-sensor-data = True
  (default: True)
verifying geometry files
C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ\inputs\building-geometry\zone.shp
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
getting geometry materials
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using 3 CPU's
Building B155084 done
Generating geometry for building 1 completed out of 14: B155084
Building B9083954 done
Generating geometry for building 2 completed out of 14: B9083954
Building B2367087 done
Generating geometry for building 3 completed out of 14: B2367087
Building B155082 done
Generating geometry for building 4 completed out of 14: B155082
Building B155068 done
Generating geometry for building 5 completed out of 14: B155068
Building B2367183a done
Generating geometry for building 6 completed out of 14: B2367183a
Building B155128b done
Generating geometry for building 7 completed out of 14: B155128b
Building B155069 done
Generating geometry for building 8 completed out of 14: B155069
Building B2367183 done
Generating geometry for building 9 completed out of 14: B2367183
Building B155083 done
Generating geometry for building 10 completed out of 14: B155083
Building B155080 done
Generating geometry for building 11 completed out of 14: B155080
Building B2367183b done
Generating geometry for building 12 completed out of 14: B2367183b
Building B155128 done
Generating geometry for building 13 completed out of 14: B155128
Building B155128a done
Generating geometry for building 14 completed out of 14: B155128a
Sending the scene: geometry and materials to daysim
         radiation_main: rad.base_file_path: c:\users\sum\appdata\local\temp\default_materials.rad
         radiation_main: rad.data_folder_path: c:\users\sum\appdata\local\temp
         radiation_main: rad.command_file: c:\users\sum\appdata\local\temp\command.txt
Traceback (most recent call last):
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 502, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.radiation)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 170, in radiation_singleprocessing
    weatherfile = epwreader.epw_reader(weather_path)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\epwreader.py", line 46, in epw_reader
    epw_data = result[~((date_range.month == 2) & (date_range.day == 29))].reset_index()
NameError: global name 'result' is not defined

         radiation_main: rad.rad_file_path: c:\users\sum\appdata\local\temp\geometry.rad
Could you please give me hint, what I should do?

Best,

Matthias

Von: Sulzer, Matthias
Gesendet: Donnerstag, 9. April 2020 11:30
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com<mailto:reply@reply.github.com>>; architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

Rey, you are the best! Many thanks.

Von: Reynold Mok <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Donnerstag, 9. April 2020 11:20
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch<mailto:Matthias.Sulzer@empa.ch>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> you would have to rerun the radiation script also since the previous radiation results would still have the leap day.

**Comment by matthiassulzer** [comment]
… and there might be an anther calculation error in the graph:
Installed Capacities for sys_42_0 - MBS Case Study HQ
--> seasonal storage with 50MW capacity is not feasible

Best,

Matthias

Von: Sulzer, Matthias
Gesendet: Dienstag, 21. April 2020 09:02
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com>; 'architecture-building-systems/CityEnergyAnalyst' <CityEnergyAnalyst@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

Hi Rey

I just identified another bug in the graph:
Annual Costs for best individuals after 100 generations normalized to gross floor area
--> the cost are showed in absolute numbers instead of US$ per m2 GFA

Best,

Matthias

Von: Sulzer, Matthias
Gesendet: Montag, 20. April 2020 19:53
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com<mailto:reply@reply.github.com>>; 'architecture-building-systems/CityEnergyAnalyst' <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: 'Mention' <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

… interesting: using Zürich SMA 2016 weather data, the error occurs. But using Zürich TMY 1990-2010 weather data, on error occurs.

Von: Sulzer, Matthias
Gesendet: Montag, 20. April 2020 19:40
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com<mailto:reply@reply.github.com>>; 'architecture-building-systems/CityEnergyAnalyst' <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: 'Mention' <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

Hi Rey

Everything worked out well with the HQ case…. up to now. I got the following error:
City Energy Analyst version 3.1.0
Running `cea radiation` with the following parameters:
- general:scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- radiation:buildings = []
  (default: [])
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:consider-intersections = False
  (default: False)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = C:\Users\sum\Documents\CEA\CityEnergyAnalyst\Dependencies\Daysim
  (default: C:\Daysim\bin)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
- radiation:write-sensor-data = True
  (default: True)
verifying geometry files
C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ\inputs\building-geometry\zone.shp
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
getting geometry materials
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using 3 CPU's
Building B155084 done
Generating geometry for building 1 completed out of 14: B155084
Building B9083954 done
Generating geometry for building 2 completed out of 14: B9083954
Building B2367087 done
Generating geometry for building 3 completed out of 14: B2367087
Building B155082 done
Generating geometry for building 4 completed out of 14: B155082
Building B155068 done
Generating geometry for building 5 completed out of 14: B155068
Building B2367183a done
Generating geometry for building 6 completed out of 14: B2367183a
Building B155128b done
Generating geometry for building 7 completed out of 14: B155128b
Building B155069 done
Generating geometry for building 8 completed out of 14: B155069
Building B2367183 done
Generating geometry for building 9 completed out of 14: B2367183
Building B155083 done
Generating geometry for building 10 completed out of 14: B155083
Building B155080 done
Generating geometry for building 11 completed out of 14: B155080
Building B2367183b done
Generating geometry for building 12 completed out of 14: B2367183b
Building B155128 done
Generating geometry for building 13 completed out of 14: B155128
Building B155128a done
Generating geometry for building 14 completed out of 14: B155128a
Sending the scene: geometry and materials to daysim
         radiation_main: rad.base_file_path: c:\users\sum\appdata\local\temp\default_materials.rad
         radiation_main: rad.data_folder_path: c:\users\sum\appdata\local\temp
         radiation_main: rad.command_file: c:\users\sum\appdata\local\temp\command.txt
Traceback (most recent call last):
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 502, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.radiation)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 170, in radiation_singleprocessing
    weatherfile = epwreader.epw_reader(weather_path)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\epwreader.py", line 46, in epw_reader
    epw_data = result[~((date_range.month == 2) & (date_range.day == 29))].reset_index()
NameError: global name 'result' is not defined

         radiation_main: rad.rad_file_path: c:\users\sum\appdata\local\temp\geometry.rad
Could you please give me hint, what I should do?

Best,

Matthias

Von: Sulzer, Matthias
Gesendet: Donnerstag, 9. April 2020 11:30
An: 'architecture-building-systems/CityEnergyAnalyst' <reply@reply.github.com<mailto:reply@reply.github.com>>; architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: AW: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)

Rey, you are the best! Many thanks.

Von: Reynold Mok <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Donnerstag, 9. April 2020 11:20
An: architecture-building-systems/CityEnergyAnalyst <CityEnergyAnalyst@noreply.github.com<mailto:CityEnergyAnalyst@noreply.github.com>>
Cc: Sulzer, Matthias <Matthias.Sulzer@empa.ch<mailto:Matthias.Sulzer@empa.ch>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Solar Potential Calculation on HQ (#2645)


@matthiassulzer<https://github.com/matthiassulzer> you would have to rerun the radiation script also since the previous radiation results would still have the leap day.

**Comment by reyery** [comment]
@matthiassulzer for the problem regarding solar radiation, there seems to be an error in the weather file reader when something else was merged. I have a fix for that and am testing now. For the other two, I would have to look further into them.

**Comment by JIMENOFONSECA** [comment]
Hey rey, we did a fix when people included weather files with a leap year but without the 29th of feb.

It should work for both cases.

Is there an error?

Dr. Jimeno Fonseca
Senior Researcher
SEC | ETH Zurich

Read more about City Energy Dynamics<https://www.jimenofonseca.com/>

On 21 Apr 2020, 20:54 +0800, Reynold Mok <notifications@github.com>, wrote:

@matthiassulzer<https://github.com/matthiassulzer> for the problem regarding solar radiation, there seems to be an error in the weather file reader when something else was merged. I have a fix for that and am testing now. For the other two, I would have to look further into them.

**Comment by reyery** [comment]
@JIMENOFONSECA I think there was a missing variable when you resolved the merge conflict. I will merge the fix soon

**Comment by reyery** [comment]
@matthiassulzer I am not too familiar with the calculation of **Installed Capacities**, could you create this in a new issue so that we can assign it to someone with that knowledge?

**Comment by reyery** [comment]
@matthiassulzer I have merged the fix for the weather reader to master. #2706
