### ISSUE TITLE
Error installing CEA

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3246]
Unfortunately I needed to delete and install CEA new. 
When I try to open the CEA Dashboard "CEA has encounted an error on startup" - can anybody help me?

![image](https://user-images.githubusercontent.com/73158684/192816436-46bdfca1-b7e8-4e00-8ec9-88562d381b21.png)

**Comment by justinfmccarty** [comment]
I just encountered this problem with one of my Masters students. She can run CEA with the console while this error comes from GUI.

**Comment by Mar-Ges** [comment]
Yes! I just tried it a few minutes ago - its a short-term solution :) 

Long-term I'd love to have both possibilities!

**Comment by jimenofonseca** [comment]
Yep. same error in other machines. @shanshanhsieh anybody planning a hotfix :-). I am a bit rusty in that regard.

 I am giving a seminar on Tuesday on CEA, so we may have to then go for older versions, right? Any advice on what ist the most stable version now?
 
 @justinfmccarty good to hearing from you :-)
 
 Best, Jimeno

**Comment by lguilhermers** [comment]
@Mar-Ges  this issue was addressed in the new release (https://github.com/architecture-building-systems/CityEnergyAnalyst/discussions/3264). Can you try reinstalling CEA and check if it works for you now?

**Comment by Mar-Ges** [comment]
@lguilhermers unfortunately its still broken (I'll tried it again for three times...)

**Comment by lguilhermers** [comment]
This issue is also being tracked here: https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/3255

Another user was able to install following this link:
https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.32.0/Setup_CityEnergyAnalyst_3.32.0.exe

Can you please try one more time and let use know if it worked? Thanks!
