### ISSUE TITLE
Importing Database via the Database initializer not possible

### ISSUE THREAD

**Issue by KFSchlager** [architecture-building-systems/CityEnergyAnalyst#3509]
**Describe the bug**
Not possible to browse for Databases path (sign to klick on it appears, but left klick doesn't open anything)
Only CH and SG Databases show up
When running Script with CH or SG Database an Error occurs:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:
'project path       ...\\inputs\\technology\\archetypes\\CONSTRUCTION_STANDARD.xlsx'

**To Reproduce**
1. Go to Database editor
2. Click on Import Database
3. Try selecting databases path: **+ Browse for databases path**
4. select CH or SG
5. Run Script
6. See error

**Expected behaviour**
should be able to select databases path
should be able to initialize the Database

**Screenshots**
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150781552/5f782e40-71e8-4ebb-bd0b-50871e16eb6e)

**Hardware (please complete the following information):**
 - Windows 10
 - Version of CEA v. 3.35.4

**Comment by reyery** [comment]
Hi @KFSchlager,

For the "+ Browse for databases path" button bug, we have fixed it for the GUI but you would have to manually update it on your end for now, without having to reinstall it.

You can extract the attached file and replace the `app.asar` file that is found in your CEA installation path:
e.g.
```
C:\Users\foobar\Documents\CityEnergyAnalyst\dashboard\resources\app.asar
```
[app.asar.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/14422643/app.asar.zip)

Let me know if that works for you.

**Comment by KFSchlager** [comment]
Hi @reyery 
yes, that worked. Thank you very much!

**Comment by KFSchlager** [comment]
Hi @reyery

the PermissionError still occurs, but the "+ Browse for databases path" button works now.

**Comment by reyery** [comment]
I will close this issue for now. Let me know if it is still an issue.

**Comment by moaapplepie** [comment]
Hej @ShiZhongming and @reyery. 

Thank you for your swift response, and help with this issue! I think I chose "install for me only" :)

**Comment by KFSchlager** [comment]
Hi,
I think i chose "install for me only" too

**Comment by KFSchlager** [comment]
My error log is the following:
_______________________________
City Energy Analyst version 3.35.4
Running `cea data-initializer` with the following parameters:
- general:scenario = C:\Users\user\Downloads\08032024test\1test
  (default: {general:project}\{general:scenario-name})
Traceback (most recent call last):
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\setuptools\_distutils\file_util.py", line 33, in _copy_file_contents
    os.unlink(dst)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\user\\Downloads\\08032024test\\1test\\inputs\\technology\\components\\CONVERSION.xlsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\datamanagement\data_initializer.py", line 70, in main
    data_initializer(locator=locator,
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\datamanagement\data_initializer.py", line 48, in data_initializer
    copy_tree(complete_databases_path, complete_output_directory)
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\setuptools\_distutils\dir_util.py", line 185, in copy_tree
    copy_file(
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\setuptools\_distutils\file_util.py", line 163, in copy_file
    _copy_file_contents(src, dst)
  File "C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\setuptools\_distutils\file_util.py", line 35, in _copy_file_contents
    raise DistutilsFileError(
distutils.errors.DistutilsFileError: could not delete 'C:\Users\user\Downloads\08032024test\1test\inputs\technology\components\CONVERSION.xlsx': Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird

- data-initializer:databases-path = C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\databases\CH
  (default: )
- data-initializer:databases = ['archetypes', 'assemblies', 'components']
  (default: ['archetypes', 'assemblies', 'components'])
Running data-intializer with scenario = C:\Users\user\Downloads\08032024test\1test
Running data-intializer with databases located in = C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\databases\CH
Copying databases from C:\Program Files\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\databases\CH
Copying databases to C:\Users\user\Downloads\08032024test\1test\inputs\technology

**Comment by reyery** [comment]
This should be resolved in the new version v3.35.5. Let me know if it is still an issue.
